<button id="button">
    <span><?= $block->escapeHtml(__('Click on ! ')) ?></span>
</button>
<h1>Hello </h1>
<iframe width="420" height="345" src="https://www.youtube.com/watch?v=tcCms15P0mI"></iframe>
<div id="modal">
    <div class="modal-body-content">
        <h2><?= $block->escapeHtml(__('Customer')) ?></h2>
        <p><?= $block->escapeHtml(__('body of the pop up ')) ?></p>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: 'Main title',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#modal'));
        $("#button").click(function() {
            $('#modal').modal('openModal');
        });
    });
</script>
